### ISSUE TITLE
Docker Exited (1), previous build worked fine

### ISSUE THREAD

**Issue by llebihan** [deasmi/unraid-tailscale#6]
Don't know if it's related but getting this message toward the end of the log

[unexpected] peerapi listen("ADDRESS") error: listen tcp6 [ADDRESS]:0: bind: cannot assign requested address

**Comment by civarson** [comment]
same issue, also reported on unraid forums.
i've since rolled back to 1.8.3

**Comment by deasmi** [comment]
Workaround is to remove the whole /mnt/user/appdata/tailscale ( or your data directory ), remove container, add from scratch and re-authenticate the new container. 

This is less than ideal.

Seems in 1.8.5+ the following error occurs as the last line.

can't change --login-server without --force-reauth

Then tailscaled exits.

I have no idea at this point what that change is, and can't find reference to this error. 

I have opened an upstream issue tailscale/tailscale#2335

**Comment by llebihan** [comment]
@deasmi ok thank you I'll keep a watch on the upstream

**Comment by deasmi** [comment]
**DO NOT DO THIS**
**LEAVING HERE FOR HISTORICAL RECORD**

I am not clear there will be a code fix, however the following script will fix your config file.

https://gist.github.com/deasmi/01fe35c9d80589890b3757d181e424e6

Needs python3, so you might need to copy tailscaled.state somewhere else.

Run as 

./config_fix.py <tailscaled.sate.filename>  > <new_config_file> 

Then copy <new_config_file> over tailscaled.state on Unraid. 
BACKUP ORIGINAL FILE FIRST.

**Comment by deasmi** [comment]
I need to ask for everyone's forgiveness as I am an idiot.

At some point in the past I managed to change the build scripts so I was accidentally building HEAD instead of numbered versions of code.

HEAD points to a development control plane hence the issues here.

Please restore you saved state file and repoint to latest or 1.10.1.
Builds are not there yet, will be hopefully this evening. 
Want to be 100% they are correct.

I will also push 1.10.1-FIXED if you want to make sure you pull the fixed version.

I am now going back to git school, going to have lie down in a dark room and will then alter the build scripts to pull binaries instead of building from source.

Apologies for all the trouble here.

**Comment by civarson** [comment]
No problem, don't be so hard on yourself! :)

**Comment by deasmi** [comment]
These builds

> 
> 
> No problem, don't be so hard on yourself! :)

I've pulled the builds for now, I want to be 100% they are correct.

**Comment by deasmi** [comment]
@blueturtleshells  @llebihan would one/both of you mind switching to dev-1.10.1 tag.

This is now pulling binanies rather than compiling, so will avoid problems like this in the future I hope.

I don't want to push this as latest until someone else has validated.

Thanks

**Comment by deasmi** [comment]
New build pushed tagged as latest, 1.10.1, 1.10.1-BINARY.

**Comment by llebihan** [comment]
@deasmi its been a hectic couple of days but the dev tag did work. I'll switch it back to latest. Thanks for your help!
